apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-234613-his1-service
spec:
  selector:
    app: enterprise-system-234613-his1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
